### PR TITLE
Add player icons to the killfeed

### PR DESCRIPTION
**Pull request by andreyrk**
## Status
READY

## Description
Implements the feature discussed in #725.

killfeed

OBS: Also slightly tweaked the hitterIcon centering.

## Steps to Test or Reproduce
Fetch the changes and trigger the killfeed in-game.

### CODE REVIEW

**Comment by eps0003** [comment]
I’m against adding more things to the killfeed because it makes it too cluttered.

**Comment by Harrison-Miller** [comment]
Yeah I agree, this change just adds more to an already cluttered kill feed.

**Comment by AsuMagic** [comment]
Plus kill messages are slow enough to render already because GUI draw calls are expensive, which is not ideal. That can be seen in the scoreboard which has got increasingly slower over the years.

**Comment by andreyrk** [comment]
Thx for the feedback, that's understandable 👍

**Pull request closed without merging**
