### PR TITLE
Refill bucket using water bomb

### PR DESCRIPTION
**Pull request by Nananas**
## Status

- **IN DEVELOPMENT**: this PR is still in development, but you would like your changes reviewed.

## Description

Allow refilling of buckets using water bombs. Related to #788. This implementation is very simple. As such, it allows an "unlimited" buckets to be filled with a single water bomb. No water quantity calculations etc are done, but I do not feel they are required. Currently the buckets are also filled fully (3 splashes). 

Thoughts?

## Steps to Test or Reproduce

- spawn empty bucket(s)
- buy water bomb, let it explode on the buckets
- buckets are now full of water

### CODE REVIEW

**Comment by Harrison-Miller** [comment]
This is a duplicate issue of: https://github.com/transhumandesign/kag-base/issues/788
Please review existing issues before creating a new one.

**Comment by Harrison-Miller** [comment]
can you modify this to also include water arrows.

**Comment by Nananas** [comment]
Now it should work for water arrows and bombs.

**Comment by Harrison-Miller** [comment]
WRT to unlimited buckets from a single water arrow/bomb. You could add a tag to the hitter blob when it fills a bucket, and check for that before filling.

**Comment by Nananas** [comment]
Thanks for the help. Didn't think of tagging. I have added the 'water quantity calculations' too.
How does this affect synchronization with other players, though? Will they have the same buckets filled?

**Comment by Harrison-Miller** [comment]
Yeah that's a good question, I think the onHit hooks should be called in the same order. However to be safe you could check is this is the server before doing the logic then sync the filled property of the bucket. You need to check somewhere in the bucket logic to update the animation.

**Comment by Nananas** [comment]
Now it should calculate refill on the server and use `sendCommand` to sync client's animation/filling.
I tried using `Sync()`, but that did not work well in combination with the `sendCommand`.

**Pull request merged**
