### PR TITLE
Bunnie's Mapcycle Update

### PR DESCRIPTION
**Pull request by bunniewormy**
## Status

(pick one)

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

- Reorganised folder structure, considering #mapcycle is dead 
- Removed 8 maps, added 8 maps, modified 5 maps

### Maps removed:

Ej_Cataracts - bad resource spread, bad mid which is not fun for any classes, the water passages make the map seem to be focused for rats but then the map is the most anti-rat with all the bedrock

ffsff_PlatformFlats - mid is too high compared to the 1st flag, yet again mid which is unfun to play, ratting too much of an advantage

Mazey_Junctions - map is too dependent on builders, way too easy to pubstomp once you skybridge to the 2nd flag (which is also too high), bad and boring mid

MonsteriCTF3 - awful gold placement, too easy to rat on, bad mid with too many trees, flag is too easy to defend due to height advantage

Radioactive_Gaps - bad resource placement, the gaps rarely actually impact the gameplay, usually ends in less than 10 minutes due to the bad flag placement, other than that the mid is boring

Shadowor_ProvingGrounds - stalemate map, sky is too low, too friendly to rats, every game on this map on a full server lasts at least 1 hour, bad terrain

SJD360_Abrogation - defending tower too easy, ratting way too good, bad resource placement

SJD360_Stampede - too small, awkward combat, mid island is too high, ratting too good again

### Maps changed:

Fuzzle_Stale - moved tent to the island on water [tent was too close to flags - stalemates]

Magmus_holegmus - removed 2 trees on each side [to make building tower easier]

Punk123_SkinnedCastle - changed the caves to not be so friendly to rats 

Skinney_Crypt - made mid a bit lower

### Maps added:

Biurza_Rule_Lawyering - original mid, worth trying out

Bunnie_JanEuborodo - wanted to try a completely flat map, yet with an interesting mid

HomekBunnie_Szkolna17 - a bit smaller than usual but i want it tried out on pubs as well

HomekBunnie_MajorSuchodolski - wanted a big map yet with a simple mid, should be fun

Coroz_floating_rifts - experimental island map, edited it quite a bit [original version on forums]

bunnie_Warbreaker - should be fun

Magmus_Hangingmus - should be fun

NewTortuga - brought it back because why the hell not, give it another chance

### CODE REVIEW

**Comment by Panky123** [comment]
Coroz map is shit its almost as bad as your floating island map(elantris). Having the creator of as less and elantris trying to edit my maps is the biggrst meme ive ever seen. The description for this map build should be: remove maps, add maps from bunnie and friends. Editting maps that have been in the game for years(Crypt) are you shitting me?. Every single new map youre trying to add is worse than platform predicament full stop.

**Comment by bunniewormy** [comment]
> Coroz map is shit its almost as bad as your floating island map(elantris). Having the creator of lech_walesa and elantris trying to edit my maps is the biggrst meme ive ever seen. The description for this map build should be: remove maps, add maps from bunnie and friends. Editting maps that have been in the game for years(Crypt) are you shitting me?. Every single new map youre trying to add is worse than platform predicament full stop.

Elantris is one of the most liked maps in pubs, what are you talking about? all you're saying is that these changes are bad and provide no arguments. I've specified my problems with the maps I've removed and you can see yourself that these are the most skipped maps... Stale being in the game for years doesn't mean it's not a cancer stalemate with mid being absolute shit after 20 min, or that the mid on Crypt is too high considering its width [I've literally moved it down 2 blocks only, whats your problem?]. and yes, that map of yours is shit - ignoring the awful redzone the ratting was horrible and way too encouraged. Are you going to deny all the problems with all the maps I've removed?

And what is your problem with the added maps? I couldn't find any better ones on the forums, considering most are ratmaps that people simply won't like, like this: https://forum.thd.vg/threads/ferrezinhre_collapse.28096/ https://forum.thd.vg/threads/redshadow6_rabbithole.28102/
https://forum.thd.vg/threads/ehra_erode.28041/
https://forum.thd.vg/threads/enclave.28043/
https://forum.thd.vg/threads/mindelo.27898/
[Ratting should never be the main way to play a map - I'm fine with it being an option but you still have people crying about rats on maps with lots of anti-rat terrain already]

Again, as I said, the new maps **should be tried out** and see if they're liked in pubs.

Also again, having a map in a mapcycle for years doesn't mean it's perfect or that it should stay there forever.

And what's wrong with platformed predicament? - It's a normal decent map, the general shape of the map is good, just the areas next to the tent are too big [pointless] and the resource spread isnt very good.

**Comment by furai** [comment]
We need a good way to quickly test maps. Will try to come up with some good idea that let's you quickly change/test maps on one of official servers. Probably could repurpose the modded server or spin up a new one. @jrgp do we have resources to spin new test server in EU/US?

**Comment by jrgp** [comment]
@furai yes. Please message me directly as to how many, what slot count, and which regions.

**Comment by EHRaaaa** [comment]
Map changes seem good, though I'd really like to see another mapcycle update with more experimental maps, due to most of these maps being more flat styled maps.

**Comment by Biurza** [comment]
Most of the maps bunnie has chosen to be removed from the mapcycle are indeed least fun to play on and are most likely to be voteskipped.
You can always argue about one's changed or added maps, but the worst scenario you could imagine would be that you replace an old trash map with new trash map, in which case, you'll replace them later too. You won't know if you don't try, that's first.

Secondly, @Panky123 do you notice how whenever someone states their opinion about something they provide at least some sort of argument? "Coroz map is shit its almost as bad as your floating island map(elantris). Having the creator of lech_walesa and elantris trying to edit my maps is the biggrst meme ive ever seen." - This is your opinion at best. That's not how you hold a discussion, so please, stop being a shitter and for once, elaborate your position properly.

**Comment by bunniewormy** [comment]
don't do anything with this PR yet please, Coroz's map died somewhere, i'll fix it when i'll be home [this weekend]

**Comment by Coroz** [comment]
maybe give examples with pictures next round if its not tomuch work.
and testing them would be nice.

**Comment by ferrezinhre** [comment]
Oh my this pure evil called bunnie will ruin everything again... Okay jokes aside and lets focus on maps.

Biurza_Rule_Lawyering - not fan of pre-builded tree farms but it's personal preferences, resource spread could be bit better. Mid is simple, and I think thats all. Maybe this bedrocks blocks.

Bunnie_JanEuborodo - flat map but also rat's haven, and  if things started to deteriorate we will have nice big pit. Otherways could lead to stalemate, anyway isn't bad, medicore, something fresh.

HomekBunnie_Szkolna17 - everything is fine at first glance then... first flag. It can be easily entombed, and you have two options to get this flag, complete destruction of defenders structures or ratting. 

HomekBunnie_MajorSuchodolski - just a simple map.

Coroz_floating_rifts - floating islands, I big fan of these maps so I can't have opinion on this one.

Magmus_Hangingmus - deterioration could be problematic, well seems fine map.

bunnie_Warbreaker - 220 gold during build time, how lovely to have two tunnels and ballista with explosive bolts at start of game, or quarry and there is additional 120 gold... wonderful!

NewTortuga - why not.

Anyway every of these maps need be tested and probably no-one will read this.

side note: Elantris is medicore.

**Comment by Panky123** [comment]
@Biurza i replied on several different platforms but if you insist on complaining about me not making a thorough critique here. To me it is obvious lech_walesa doesnt belong in the cycle and I find it ironic the creator is nitpicking others work. That's what any honest interpretation of my statement meant and although it wasnt worded nicely it was more than shittalk. Beyond that coroz gold floats is bad sky island map in the same vein as elantris( its ok if you didnt get that i understand most people dont know all the maps in the cycle by name but it isnt fair to pretend like a statement is meaningless because you dont know the context). Beyond that bunnie just makes arguments up like his maps(elantris) are the most popular on pubs. He has no way of knowing that even if he plays 3+ hours of pubs a day he doesnt interact with the whole of the community. Everything said here is pretty just opinions and im not interested in being lectured on civility when maps that Ive put a sizeable amount of effort into making the best i could are edited while objectively bad maps are allowed to exist let alone untouched(again levy_walesa). Finally id just like to make it clear that if you need flatmaps the mapfolder has better(bluesunset, grounds, if i wasnt to suck myself off platformed predicament). Need better water maps? Try aqueduct or typhoons. Need more interesting maps? Try dahill, porkbuns ECT. This entire mappool suggestion isnt made in good faith or in the best interest of the map cycle. Outright insulting someone because they dont like the new informal council(circlejerk tbfh)'s new map build is certainly more "shitter" tier than anything ive said.

**Comment by bunniewormy** [comment]
closed because of incompetent people

**Pull request closed without merging**
