### PR TITLE
Removed Gloryhill2 and added the updated version, called 8x_Gloryhill.png

### PR DESCRIPTION
**Pull request by ewetcr**
## Status

(pick one)

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
- **IN DEVELOPMENT**: this PR is still in development, but you would like your changes reviewed.
- **HOLD**: you are aware of some serious issues with your PR. It should not be merged and you will follow up when they are fixed.

## Description

A few sentences describing the overall goals of the pull request's commits.

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

If you added new features and want to explain how to use them, do so here.

Some useful information to include:

- git branch used
- gamemode if relevant
- specific objects or behaviours affected

### CODE REVIEW

**Comment by Mazey** [comment]
Several changes we need to see before merging this:
-Increase the skybox height and width of the map (either your own version or copy from the recent version);
-Remove Maps/CTF/Dormant/8x_GloryHill.png;
-Update the CTF map cycle to point to GloryHill instead GloryHill2 since you’re removing the 2016 version.

**Comment by ewetcr** [comment]
I'll edit the mapcycle as soon as I get back from some days off; regarding the first requeriment, I won't go through it as Ni already accepted the changes and doing that would soften the original idea of what the map always offered.

**Comment by Ni-ice** [comment]
@ewetcr What changes have I accepted? 
I don't recall managing CTF maps in the past. 

Are you mistaking me with someone else?

**Comment by ewetcr** [comment]
Discord_2019-04-17_18-59-53
This was january 4th, after I uploaded via discord the modifications I made. In case there are 2 Nis, you this was accepted.

**Comment by Mazey** [comment]
I wrote a response after your previous comment but I don't see it - I guess I never submitted it. So here goes again:

> I won't go through it

Changes were made for a reason, when you submitted your map in 2016 you accepted we could make changes as we see fit - and you've recently acknowledged this on Discord. I don't see why you're saying Ni agreed with those changes: that was January - before we slightly increased the dimensions of a bunch of maps as well as yours - and Ni doesn't deal with the CTF mapcycle.
Your changes are very welcome and I'd gladly merge them in, but removing recent changes for no good reason (map has been a lot of fun and suits the current meta better) is counterproductive and to continuously bring this up is really bothersome.
If you still don't want to take the newest version and apply your changes to it, I can only see one other option: to merge these changes in and remove your map in good faith from the mapcycle and move the map to the Dormant folder.

For what it's worth, you still need to remove the original 2016 version we kept around in Maps/CTF/Dormant.

**Comment by Ni-ice** [comment]
@ewetcr @Mazey
Alright sorry guys, I don't recall why I said that the changes are being implemented in the next build, due to me not handling ctf maps. I myself thought we (Me, Mazey, Geti and Potatobird)  had agreed on accepting them - But it seems I wasn't right. I'll let you two handle this from here, sorry for the confusion, I'll stay out of further Ctf map businesses for now.

**Comment by ewetcr** [comment]
> removing recent changes for no good reason (map has been a lot of fun and suits the current meta better) is counterproductive

The map plays actually worse than it is supposed to, as the meta developed to a intensive use of teleporters, siege and quarries, and the old map display doesn't hold that style of gameplay. Due to its size and characteristics, it's prepared (and has been updated twice in that regard) to promote a more close quarters development, to instigate the players to get to mid by themselves and play together, thanks to the overall lines of the terrain and the limitations of the resources it offers.
I just removed the dormant version, but the map I added remains the same. If that's not valid for the changes being added, I'll end it here.

**Pull request closed without merging**
