### PR TITLE
[modified] TDM maps fixes (thanks Biurza!)

### PR DESCRIPTION
**Pull request by Mazey**
## Status

 **READY**

## Description

Fixes a bunch of TDM maps by Biurza (details below). Tested by Niii and Geek.

```Amarok:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
ArcherPoint:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Added a bush on the left side, same place where one was placed on the right side.
BleakArena:
-Skipped (Not used)
BorgRuins:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Cloister:
-Skipped (Intentional)
CraggyOutlook:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
CrampedCastle:
-Skipped 
Dichotomy:
-Skipped 
Filthpit:
-Skipped 
ForgottenHero:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
FortMercury:
-Skipped (Not used)
GamblersDen:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
HeraldsMarshes:
-Skipped
HergestRidge:
-Skipped (Not used)
Labyrinth:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
LonelyTreasure:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Ommadawn:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Moved red trader 1 block to the left so it's symmetrical now.
PressureCooker:
-Skipped
RattleCage:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
RoyalTomb:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
RumbleGround:
-Skipped
SkyFortHiggins:
-Skipped (Intentional)
TheCauldron:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Vault:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
//Community Maps
8x_Airwater:
-Skipped (Not used)
8x_Cascade1:
-Skipped (Intentional)
8x_Dirtkissing:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Moved red trader 1 block to the left so it's symmetrical now.
8x_DownShot:
-Skipped (Not used)
8x_Level2:
-Skipped (Not used)
8x_Mandala:
-Skipped (Intentional)
8x_Stinger:
-Skipped (Not used)
8x_TDM1:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Moved red trader 1 block to the left so it's symmetrical now.
-Moved both traders 1 block higher as they were half way underground before.
8x_TDM2:
-Skipped (Intentional)
AsuMagic_Waterfalls:
-Skipped (Not used)
Bastille:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
bunnie_Korwin_Mikke:
-The one file in the Community folder isn't used, but there's second version of this map in folder "Dec17" that is used. 
-Moved red spawn-point 1 block to the right so it's symmetrical now. (Still, until noticed it, kinda fixed it)
Bunnie_TDM1:
-Skipped (Not used)
Bunnie_TDM2:
-Skipped (Not used)
Bunnie_Wojciech_Jaruzelski:
-Skipped (Not used)
Cohen_Sanctuary:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
GurinTDM1:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
GurinTDM2:
-Skipped (Not used)
GurinTDM3:
-Moved blue spawn-point 1 block to the right so it's symmetrical now.
JoikenTDM1:
-Skipped (Not used)
JoikenTDM2:
-Skipped (Not used)
kodysch_Upshoot:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Lavaguy678_Peanut:
-Skipped (Not used)
Lavalord_TDM1:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Moved red trader 1 block to the left so it's symmetrical now.
Lavalord_TDM2:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
mcrifel_Ruin:
-Skipped (Not used)
MonsteriTDM1:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Replaced right blue trader with red trader, as there were 2 blue traders on the map.
MonsteriTDM2:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
SSP_Crown_of_the_Ancients:
-Skipped (Not used)
Whichway:
-Skipped (Not used)
//Dec17
8x_Virgo:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Biurza_Stompy_Bois:
-Skipped (Not used)
bunnie_Korwin_Mikke:
-Moved red spawn-point 1 block to the right so it's symmetrical now. (This is the one actually used, idunno why is there a duplicate in Community folder)
Ferrezinhre_CursedWell:
-Moved red spawn-point 1 block to the right so it's symmetrical now.a
-Moved both chests 1 block above ground before spawn, as they tend to get set improperly if chest pixel is placed directly on the ground in the png file.
Ferrezinhre_Neringa:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Ferrezinhre_Reaver:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Niiiiii_Watery:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
//Dec18
Biurza_Cock_Fight:
-Skipped
Biurza_Retroactive_Interference:
-Skipped
FG_Break:
-Skipped (There were other issues with the map so I think FG or Ni will fix it themselves)
FG_SpaceInvader:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Super_Gaming_Geek_Trilevel:
-Skipped
Vans_Ziraeth:
-Skipped (Not used)
//May18
Ferrezinhre_Vertigo:
-Skipped (Not used)
FG_Clash:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
FG_Enclosure:
-Skipped (Not used)
Niiiiii_Elewater:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
Niiiiii_GetisArena:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
-Swapped blue and red spawn-points as it's traditionally blue on the left and red on the right.
//Oct16
Eluded_JoansMansion:
-Moved red spawn-point 1 block to the right so it's symmetrical now.
SJD360_CrowbarsSwitchblades:
-Skipped (Not used)
//Oct18
Vans_Corruptio:
-Skipped
Vans_Spelunca:
-Skipped```

### CODE REVIEW

**Comment by Ni-ice** [comment]
If you add this now the new maps I've modified won't be added right?
All of my maps have been edited eg. if you add them again now it will break the mapcycle.

**Comment by Mazey** [comment]
@Ni-ice this doesn't break the mapcycle but it could overwrite maps that you've changed since this was made and has already been merged. I won't have access to a pc for a while, maybe you could look into which maps need to be excluded from these changes.

**Comment by Mazey** [comment]
It has been tested thoroughly tested by Geek and Ni. As I’ve said, Ni just has to check which maps he has already changed since this “map fixes pack” was made.

**Comment by furai** [comment]
And that's what I'm asking for. To test if map fixes weren't overwritten. There are visual diff tools that might help with the task.

@Ni-ice if you need help with that - try catching me on discord.

**Comment by Ni-ice** [comment]
These are the 5 maps that have been modified and shouldn't be reverted with this pr :

FG_Break.png
super_gaming_geek_Trilevel.png 
Niiiiii_GetisArena.png 
Niiiiii_Watery.png 
Niiiiii_Elewater.png

**Comment by furai** [comment]
Ok, do your fixes also include now fixes from @Biurza?

**Comment by Ni-ice** [comment]
Yes, these 5 maps are completely fixed already. 
Here's the pr: https://github.com/transhumandesign/kag-base/pull/465

**Comment by furai** [comment]
I'll see what I can do.

**Comment by furai** [comment]
I've merged it in manually. Reverted the maps mentioned in @Ni-ice message. Can you check it if everything is correct?

**Pull request merged**
