### PR TITLE
Organized costs and descriptions

### PR DESCRIPTION
**Pull request by Diprog**
Descriptions later
Edit: they are updated too now

### CODE REVIEW

**Comment by Diprog** [comment]
I don't know where to move all these configs. And I think we need to rename "CTFShopCosts.cfg" to "CTFCosts.cfg". 
Also filled bucket is missing, you can easily add it back.

And btw, removed useless WARCosts.as includes from some files that never used that include.

**Comment by 1bardesign** [comment]
There are conflicts as part of this, you will need to pull master and carefully sort them out before this will be considered again.

Please don't rename files off-hand - because a new name might be "better" semantically or whatever, but if a mod has included or modified that file it will be broken by the change.

@fzzle please be more constructive about review; just leaving a thumbs down is demotivational and noncommunicative.

**Comment by Diprog** [comment]
> if a mod has included or modified that file it will be broken by the change

A modder will just have to edit some files. Same thing happened with materials update earlier.

**Comment by 1bardesign** [comment]
It'd be possible to reorder descriptions if we had an enum index into it and used that everywhere, but then we may as well just use string literals for sure, haha.

Materials update also caused problems with mods 🙂 we'd like to have compatibility notes and ideally a way for people to upgrade their mods easily, or pull in old versions of the files they need without having to learn about git (as many modders do not)

I'll look at merging this but we need to be clear about compatibility issues raised and communicate that to modders, if possible well ahead of it being released. That last part isn't really possible if I'm going to do an update today. We'll see if it makes it in.

**Pull request merged**
