### PR TITLE
Accolades update October 

### PR DESCRIPTION
**Pull request by bunniewormy**
## Status

(pick one)

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

- moderation accolades for newest OKSAs
- community accolades for contributors to head pack DLC, bokkusu for discord admin
- EU 1v1 knight tournament for people with no medals no. 2 https://challonge.com/yzrdorvk
+ head for Fobri
- OCE 1v1 knight tournament for people with no gold medals no. 1 https://challonge.com/4ku3vuy4
+ head for Monkey_Feats
- OCE 2v2 knight random teams tournament no. 1 https://media.discordapp.net/attachments/556537168428924941/640923575053975582/unknown.png
- Link renamed to Waxtor

### CODE REVIEW

**Comment by Harrison-Miller** [comment]
dome is missing a participation ribbon for eu 1v1

**Comment by Harrison-Miller** [comment]
Unfortunately the OCE don't seem entirely aligned with in game names. Who organized it we need them to answer who the following people are in game.
Fran, Scansa, StrategyCube,  Krocco, kawkawkawkaw.

Besides that these are the only things I found missing.

-  Buildfast - participation
- 707Beater - participation
- Cruxiat - gold medal

Thanks for the work bunnie.

**Comment by bunniewormy** [comment]
> dome is missing a participation ribbon for eu 1v1

dome is Erik22


> Unfortunately the OCE don't seem entirely aligned with in game names. Who organized it we need them to answer who the following people are in game.
> Fran, Scansa, StrategyCube, Krocco, kawkawkawkaw.
> 
> Besides that these are the only things I found missing.
> 
> * Buildfast - participation
> * 707Beater - participation
> * Cruxiat - gold medal
> 
> Thanks for the work bunnie.

Fran = FG
Krocco = Croco-Dile
kawkawkawkaw = Azakaka
Strategycube = awesomecat6 
buildfast = Buildfast115 
707BEATER = BummysOnic 
Scansa = falconwarrior812

I fixed crux

**Comment by Harrison-Miller** [comment]
ok buildfast still needs one more participation ribbon, his entry has changed. The last one it shows is OCE 3v2 open

**Comment by bunniewormy** [comment]
fixed

**Comment by furai** [comment]
@Cruxiat could you keep in mind for future tournaments to use usernames in Challonge, please?

**Pull request merged**
