### PR TITLE
Removed gold cost from boat shop

### LINKED ISSUE #573: Remove gold cost from boat shop.
**Current in-game behaviour.**

Boat shop costs 50 gold.

**Proposed Change**

Boat shop costs no gold.

### PR DESCRIPTION
**Pull request by eps0003**
## Status

- **HOLD**: you are aware of some serious issues with your PR. It should not be merged and you will follow up when they are fixed.

## Description

Resolves #573 

## Steps to Test or Reproduce

Build a boat shop

### CODE REVIEW

**Comment by eps0003** [comment]
This should be put on hold until something is done about the recently found dinghy launch bug.

**Comment by Vam-Jam** [comment]
Added WIP so somebody doesnt merge in accidentally until dinghy bug is fixed

**Comment by eps0003** [comment]
Removed WIP because the dinghy bug isn't being abused as much anymore. I still want more community feedback on this PR though.

**Comment by Harrison-Miller** [comment]
@eps0003 does warboat still have a gold cost, it's a spawn point. Probably should work the same as the new ballista idea, cost gold, drop gold.

**Pull request merged**
