### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Mazey**
## Status

- **IN DEVELOPMENT**

## Description

Dutch translation

### CODE REVIEW

**Comment by Harrison-Miller** [comment]
Bump, you should complete the translation when you get a chance, I see this still contains Russian text.

**Comment by Harrison-Miller** [comment]
Bump 2, when can this get done?

**Comment by AsuMagic** [comment]
FWIW it's okay if the translation is not complete, it should just be clarified in a comment at the start of the file or something and have the untranslated lines commented rather than left as russian

**Comment by Harrison-Miller** [comment]
Marked as abandoned and closed for now, submit a new PR if you finish this.

**Pull request closed without merging**
