### PR TITLE
All mugg PRs merged (100%? done)

### PR DESCRIPTION
**Pull request by mugg91**
## Status

- **IN DEVELOPMENT**

### TODO
- Adjust Japanese, Polish, Portuguese, Russian, Spanish, Turkish Locale files to accomodate for previous changes
- Planned: Gamestate banner tdm
- Add Lamp light power change
- Fix that closed state of spiker doesn't have bloody tip
- Fix possible issue about camera zooming when joining server
- Fix that Solar Panel still sends power even when in a dark room
- Fix spiker ejecting spike through any solid blobs
- Solve conflicts with file merging

### Important

The purpose of this PR is to quickly test all my PRs at once.
I merged all of my recent PRs with some exceptions (see below).
Old PRs of mine are left out for now, but might get added in later or on request.

### Bug Fixes
```
[fixed] CTF: Queue button in top right corner won't turn grey randomly
[fixed] TDM: Couldn't collect coins from chests in "bunnie_Wojciech_Jaruzelski_v2"
[fixed] TDM/Sandbox: Gold decaying would alert admin
[fixed] TDM_spawn and tent won't be floating above ground or be one tile too deep
[fixed] TDM: MonsteriTDM1 wrong grass tile removed
[fixed] TDM: Invincible trampolines such as in Biurza_Clogged_Pipes won't decay in water
[fixed] TTH: Dinghy scroll was invisible
[fixed] Sandbox: You won't erroneously receive twice as many materials on joining server
[fixed] Sandbox: Clicking on a component in Builder inventory no longer turns them grey anymore
[fixed] You can't use buttons or open inventory while stunned anymore
[fixed] Bison's or vehicle's damage owner did not get unset when sitting player died 
[fixed] "/scroll <name>" chat command was not working
[fixed] "/heal <amount" chat command was not working correctly
[fixed] Archers can not shoot through red barrier
[fixed] Archer could continue stabbing or charging Arrow while attached 
[fixed] wrong charge cursor for Knight and Archer while attached
[fixed] Wrong font on tips and vote window looking off when game state banners are shown
[fixed] Components had the wrong frame after rejoining the server
[fixed] "on fire" state wasn't copied when changing class
[fixed] Writing "ass" or "cock at the end of your chat message caused an exception in NoSwears.as
[fixed] Trampoline no longer bounces blobs slightly off to the side over time
[fixed] Drill was emitting steam even though there was no heat
[fixed] Greg couldn't grab you if you previously got in a Crate while grabbed
[fixed] Runner blob would spawn when getting killed while changing class
[fixed] Archer fake charging bug
[fixed] Knight doubleslash bug
[fixed] No sound when shooting your last arrow on server
[fixed] Sound effects not playing properly when constructing a building with exactly 150 wood
[fixed] That items could be auto-picked from your hand by other players or by a crate
[fixed] Obstructor and Sensor couldn't be destroyed properly
[fixed] Spiker and Dispenser will work with away-facing platform at their exit
[fixed] Several fireplaces would cook several foods from just one ingredient
[fixed] A food could heal you and be cooked in a fireplace at the same time
[fixed] Fireplace would forget that it has been extinguished when rejoining the server
[fixed] Invincible players could get hit or knocked back by certain attacks
[fixed] Blobs with bloody state update their sprite properly when changing kidssafe setting
[fixed] Fishy's air drown wouldn't reset over time when returning from air back to water
[fixed] Bomb's spark volume and speed didn't rise when explosion was nearing
[fixed] Camera issues:
	[fixed] Camera gets stuck when going spectator, a new match starts, then switching to a team
	[fixed] Camera couldn't scroll as spectator in a match with bots
	[fixed] Camera would pan somewhere else when moving character forward, then going spectator
	[fixed] Camera would initialize in position (0, 0) instead of center map on server
```

### New Features

```
[added] Water dripping effect for filled sponge and for runners who got out of water
[added] "/sign <text>" chat command
[added] "/suicide" chat command
[added] "/bot" chat command now allows setting the bot's name via "/bot <name>"
[added] "/seed <type>" chat command can now spawn grain plant, flowers and bush
[added] Crates and signs created by chat command are checked for swear words
[added] HUD background is transparent when mouse hovering
[added] Sound when Archer's Grapple collides
[added] Platforms will prevent items from getting picked up
[added] Kill feed will now show Bison and Shark icons
[added] Ballista Bolt can drop down from stuck position
[added] Resupply indicator for Archer
[added] Steak, Chicken and Fishy can be cooked by fire arrow
[added] Chicken and Fishy can be cooked by being in a fire tile long enough
[added] Winning team receives 150 coins also when other team surrendered
[added] Descriptions to components in builder block inventory
[added] CTF: Loser team's Tent will explode
[added] CTF: Mounted Bow can be purchased in vehicle shop for 80 coins
[added] TDM: Minimap icon to TDM_Ruins
[added] TDM: You can't purchase items after match ended
[added] TDM: Icons in shop are now team-colored
[added] TDM: Crate can be purchased for 50 coins
[added] Sandbox: Lamp component is now team-colored
[added] Sandbox: New component "Flamer" (req. 50 stone), throws flames when powered
[added] Sandbox: New component "Bell" (req. 10 stone, 10 wood), rings when powered
[added] Sandbox: New component "Display" (req. 30 stone), displays current power number
[added] Sandbox: New component "Solar Panel" (req. 30 stone, 10 wood), converts light to power
[added] Sandbox: Resupply indicators added
[dev] Sandbox: Support showing more than 12 blocks per page in builder block inventory
```

### Gameplay Changes

```
[changed] Sandbox will now allow faster building and mining
[changed] You can now jump on three tile tall platforms/doors
[changed] Fireplace and Egg will have collision with platforms and doors
[changed] Builder can now hit Dummy and Sign
[changed] Greg will not take fire damage
[changed] You won't get stomped by the player that you recently stomped
[changed] Archer will not shoot automatically when picking up a Trampoline or Dinghy
[changed] You won't see Crate buttons when you are attached
[changed] Seed can be placed on non-static blobs that impose no-build-area (e.g. Saw or Dinghy) 
[changed] "/spawn <blob>" chat command will spawn blob with caller's facing direction
[changed] "/team <number" chat command will also convert items in your possession
[changed] Sandbox: Trap Block can be placed
[changed] Sandbox: Non-Builder classes won't receive wood or stone on respawning
[changed] CTF: Arrows cost changed from 15 to 5 coins
[changed] TDM: You don't lose coins post and pre-match when killing yourself
[changed] Saw was changed:
	[changed] Doesn't take damage from enemy normal arrows
	[changed] Can be set on fire
	[changed] Takes 1.5 times explosion damage
	[changed] Health changed from 5.0 to 6.0
[changed] Mounted Bow was changed:
	[changed] Can be picked up by enemies if below it like Saw, unless it was pre-loaded
	[changed] Health from 2.0 to 2.5
	[changed] Adjusted some properties, it has now less drag and can't be thrown as far
	[changed] Adjusted Width to just wide enough to not fit in 1 tile gaps
	[changed] Changed inventory space from 3 slots to 2 slots
	[changed] Arrow won't despawn early
	[changed] Shoot delay from 25 ticks to 35 ticks
```

### Graphical/Audio Changes

```
[added] Spiker will have a bloody tip even in closed state
[added] Water splash from bucket, waterbomb or water arrow will clean bloody blobs
[changed] Tips on death will look better
[changed] Dispenser won't make a particle if its exit was blocked
[changed] Dispenser will make a lower sound when its exit was blocked
[changed] Sky border is slightly more blue-shaded
[changed] Keg and Drill will now gib when destroyed
[changed] Burning bush, grain_plant and flowers won't make "cut" sound effect
[changed] Shield stun sound will be played by the hit blob, not the player that shielded
[changed] The look of the builder block inventory hover text has been refined
[changed] Fireplace has a bigger smoke particle when getting extinguished
```

### Balance Changes

```
[changed] TDM: RumbleGround grain is now positioned in the center 
[changed] TDM: Biurza_Tramp_Trap now has gold ores on the right side 
[changed] SmallCTF: FG_Bigpit tree and bush positions are now mirrored
```
----

## PRs not included (yet)
```
[fixed] Blobs will void out properly (People didn't like this)
[added] automatically update files during holidays (This is a large PR, I'd like the dev's ok first)
[added] mugg1991 maps (Waiting for approval)
[fixed] Obstructor has proper minimap colors now (The solution isn't ideal)
[fixes] Wall running would override Trampoline bounce (Might be obsolete since there is trampoline rework PR)
[added] Quarters switches between beer and orange juice based on g_kidssafe (not sure it works, needs testing)
[added] Dual elbow & Fork wire components (not included for reasons outlined in the PR description)
```

### CODE REVIEW

**Comment by mugg91** [comment]
I will try to make a video show-casing all changes in the next 1-2 weeks.
After my TODO list (first post), I will be done with kag dev for a while.

**Comment by mugg91** [comment]
> I will try to make a video show-casing all changes in the next 1-2 weeks. After my TODO list (first post), I will be done with kag dev for a while.

I'm very sorry, but I have to say that I will not get around to doing more work. I reached the point where I lost interest. A writer's block you may say. I might return to kag dev work at a later point in time, but I don't know when that will be. I will still post issues as I come across them.

If you are looking to implement any changes, the issues in the "TODO" section in the first post are still unfixed so when implementing things like the "Camera fixes", you should take care. Everything else should be working as expected. This PR doesn't include command changes by bunnie though.

**Comment by mugg91** [comment]
I will just use this comment space to say:
I would love it if my changes got implemented at some point.
If you don't want to develop the game further, it would be a shame about the additions that I came up with and aren't going to get added. But at least the bug fixes should be no-brainers. I don't see what's holding back the decision to implement some of the more annoying or unnecessary bugs (doubleslash bug, archer fake charging bug, gold decaying would alert admin, to name a few).

Don't be like the developers of the [game I previously played](https://steamcommunity.com/app/204300)...

**Comment by Vam-Jam** [comment]
I'm going to close this PR, it's not possible to review it with the limited time we have. We are going to review your PR's that are focused on one or two features, as it makes reviewing and testing a lot easier.

If there are any features in this PR that are not already in another PR, could you open up pull requests?

Thanks!

**Comment by Vam-Jam** [comment]
Its easier to test when pull requests are separated with clearly defined features/steps like you have been doing (thanks for that). It makes pointing out issues and comparing between previous builds pretty simple.

When you bulk pull requests together like this, Its much harder for us to read through the code in one sitting and suggesting changes becomes significantly harder. 

We have our own process for checking merged changes, and not something you typically should worry about (KAG testing branch gets updated to the latest commit every now and then + engine changes).

**Pull request closed without merging**
