### PR TITLE
different button for healing with food

### PR DESCRIPTION
**Pull request by ferrezinhre**
Change for this request https://github.com/transhumandesign/kag-base/issues/98, unused button "v" is for food, spacebar is still for throwing things.

### CODE REVIEW

**Comment by terracraft321** [comment]
Rather interesting, we just could make a new button for food itself.. whatever.

**Comment by 1bardesign** [comment]
I like this. I'll ensure this doesn't clash with anyone's expectations and look at the engine work required to "rename" the variable while keeping mod compatibility.

**Comment by ferrezinhre** [comment]
Requested changes done.

**Comment by 1bardesign** [comment]
Thanks for the prompt changes - I'll be looking at integrating this fully next week.

**Comment by 1bardesign** [comment]
@ferrezinhre thank you for your work - this PR fixes an issue with a bounty, please email support with a paypal-capable email to claim the payment, citing this PR and the recent bounty announcement so we can match it all properly!

Please also make a post from your account on this issue with some kind of "proof" to mention in your email, as anyone could email claiming to be you to try to steal your bounty. We'll have to formalise this system better in future!

**Pull request merged**
