### PR TITLE
Allow moving spectator camera when voting for new map in CTF

### LINKED ISSUE #1026: Cannot move camera after voting for next map after match when dead
**Reproduction**

1. Finish a CTF match
2. Vote for a map

**Expected Behavior**

You should be able to move the camera like normal

### PR DESCRIPTION
**Pull request by laws65**
## Status
- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description
Makes it so that you can move the spectator camera when voting for a new map in CTF. Resolves #1026

## Steps to Test or Reproduce
- Finish a CTF match
- Die or switch to spectator
- Vote for a map
- Move around as spectator

### CODE REVIEW

**Comment by Vam-Jam** [comment]
Won't this cause your camera to move when you try to click on one of the vote options

**Comment by laws65** [comment]
Merge when

**Review by AsuMagic — APPROVED** [review]

**Comment by mugg91** [comment]
I noticed when I switch from spectator to a team mid match, I cannot scroll the camera for the duration of the spawn timer. 
Just saying, since that's similar to the issue at hand.

**Comment by laws65** [comment]
Ok

**Pull request merged**
