### PR TITLE
Mine ownership changes, food ownership, draw owner username on mouse hover

### LINKED ISSUE #825: Add some visual indication for your own mines.
Because it's important to know if that one mine will kill not only enemies, but also you. Perhaps a slightly different color?

### PR DESCRIPTION
**Pull request by bunniewormy**
## Status

(pick one)

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

merges https://github.com/transhumandesign/kag-base/pull/896, https://github.com/transhumandesign/kag-base/pull/894, adds OwnerCommon.as

resolves #825

### CODE REVIEW

**Review by AsuMagic — APPROVED** [review]

**Review by AsuMagic — DISMISSED** [review]

**Review by AsuMagic — APPROVED** [review]

**Review by AsuMagic — APPROVED** [review]

**Comment by eps0003** [comment]
Why is there a need to know the ownership of food?

**Comment by CatWiz** [comment]
Make it show the owner only  if player is holding control

**Comment by bunniewormy** [comment]
> Make it show the owner only if player is holding control

I don't think a hardcoded button should be used for things like these. Some people already reported issues with not being able to do lcontrol zooms, plus the text isn't really obstructive

**Comment by eps0003** [comment]
I'm gonna close this just because my PR was merged instead of this one.

**Pull request closed without merging**
