### PR TITLE
The map vote screen now has 4 maps as options

### PR DESCRIPTION
**Pull request by Hobey**
- **READY**

Example:
Example

The map vote screen now has 4 maps as options, and no 'random map' option.
In case of tie, it will pick one of the maps with the most votes at random.

_I think this is a more fun map vote system than the current one._

---
sorry about the inconsistent indentation causing extra line diffs in the commit

### CODE REVIEW

**Comment by eps0003** [comment]
Please fix the messy diff so it's easier to review and merge.

**Comment by Hobey** [comment]
I'm won't edit this branch; I'm exhausted.

**Comment by Hobey** [comment]
I'm back.

Commit 0c173bd cleaned up the diff as requested.

**Comment by Hobey** [comment]
Actually, PostGameMapVotes.as still had messy diffs, fixed PostGameMapVotes.as now with commit c1bfe51.

**Comment by CatWiz** [comment]
Imo 4 maps is too many for 16-24 players, I'd keep it at 3

**Comment by AsuMagic** [comment]
I fixed the merge conflict. That being said this will need some more testing just in case since the map vote code has changed slightly since the PR was made. Also further PRs (from anyone) would be welcome to refactor the code later to resolve the added TODO.

**Comment by Hobey** [comment]
I just had this stupid thought about the [3 maps or 4 maps] question. We could make it randomly 3 or 4.

Part of me still wants to finish my map browser thingy and make it so that people can just suggest maps in the vote time. IMO that would be a nicer system, though I'm not sure if it would get messy with loads of people in the server.

**Comment by Hobey** [comment]
image of the map browser project for reference: https://github.com/transhumandesign/kag-base/pull/993#issuecomment-1312738010

**Pull request closed without merging**
