### PR TITLE
Modified emote wheel to include more emotes.

### PR DESCRIPTION
**Pull request by Shylie**
## Status

**READY**

## Description

Modified emote wheel to replace useless emotes (wall, fire, note) with unused emotes (wink, cool, clap).

## Steps to Test or Reproduce

Use emote wheel.

## Other information

Pointing emotes should still be lined up.

### CODE REVIEW

**Comment by benjamingorman** [comment]
@Shylie maybe include a screenshot of what it looks like with the change? The main argument against it would probably be making the wheel too cramped. Also as eps said, changing muscle memory - but I think having access to a wider set of emotes outweighs that.

**Comment by 1bardesign** [comment]
Considering I've been asked every single build for the last 6 months "when `:kag_cool:` and `:kag_clap:` ingame??" I honestly welcome them being added. A screenshot comparison would be appreciated though.

**Comment by Shylie** [comment]
New commit to revert most changes since I was getting negative feedback.
Wall, fire, and music note have been replaced with wink, cool, and clap.

new version after commit

**Comment by Shylie** [comment]
> Although I would love more emotes, it’ll just mess with muscle memory. Emotes on the emote wheel should be replaced, not added.

This has been done with the latest commit. Thank you for your feedback.

**Comment by Shylie** [comment]
eps's emote binder changes cover the main point of this change-- adding kag_clap. closing this pr. #348

**Pull request closed without merging**
