### PR TITLE
Create japanese_ja.json

### PR DESCRIPTION
**Pull request by kinokino7**
[Uploading Base.zip…]()

### CODE REVIEW

**Comment by 1bardesign** [comment]
Thank you for this - we will need to add CJK font support before merging this as in its current state, it will add a broken menu item to the list and confuse people. We will try to add such support in the next month or so.

Very glad to see some asian language translation efforts though, it has been missing for a long time.

**Comment by kinokino7** [comment]
It is nice to be of some use.
I would like to translate the description of MOD server if I can.
However, I do not know how to change the data of the sentences corresponding to the MOD server.

**Comment by 1bardesign** [comment]
For modded server text:

You can look for the strings to translate in the source code but the author will need to have used the translation functions to actually make the strings accessible to translation.

If not, and you can find the author, you can ask them to - or if not, you could release a version of the mod with proper translation functionality added.

For the big modded servers (TC for example) the authors are generally available to ping in `#modding` channel on discord.

**Comment by 1bardesign** [comment]
Hello @kinokino7 !

New **test build** has required support to swap fonts for other languages 🎉 

You just have to provide translations for the font filename, like this (copied from chinese translation)

```
"GUI/Fonts/DejaVu/DejaVuSans.ttf": "GUI/Fonts/SourceHan/SourceHanSansCN-Regular.ttf",
"GUI/Fonts/DejaVu/DejaVuSans-Bold.ttf": "GUI/Fonts/SourceHan/SourceHanSansCN-Bold.ttf",
```

If you could
- apply for test build on forums [here](https://forum.thd.vg/forums/for-thd-tester-status.119/) if you dont already have it, and download test build to test your changes
- join `#testing` channel on discord to discuss any troubles you have, or use `#development` like I think you already have if that is easy for you?

That would be great! 🙏

If not, can you at least let us know what font you we should use with these translations - I'm not sure if Source Han JP fonts from here https://github.com/Pal3love/Source-Han-TrueType are ok or if there are smaller, JP compatible, game-friendly fonts?

**Comment by kinokino7** [comment]
Fonts to be used>

The font I used is free and is based on a modifiable font.
It will be displayed without problems when displayed in the game
The translation content has been adjusted by me.

**Comment by 1bardesign** [comment]
@kinokino7 can you please clarify what you mean? There was no font attached to this pull request, and there's no update for a while.

We have support for swapping fonts for different languages in-game now, so if you can add the required fonts (or just check if source han jp is a good fit) and required strings to use them in game, we can get this translation included with the vanilla game soon!

**Comment by kinokino7** [comment]
[Base.zip](https://github.com/transhumandesign/kag-base/files/2960246/Base.zip)

sorry,I forgot to attach the file.
Among them, the data translated into Japanese,
Contains font data for Japanese.

Font data source>
http://jikasei.me/font/genshin/#_7
Translation of font data license part>
"Genshin Gothic" is a modification of "Genno Koji Gothic".
It also contains some character glyphs derived from "M + OUTLINE FONTS".
"Adobe" owns the copyright of "Glyphs derived from Gothic font" included in the font data.
The copyright of "M + OUTLINE FONTS derived character glyph" included in the font data is owned by "M + FONTS PROJECT".
The font files of "Genshin Gothic" can be used under the same "SIL Open Font License 1.1" as "Genno Koji Gothic", so they can be used without restriction in commercial use. Please see the font license page for details.

**Comment by 1bardesign** [comment]
@kinokino7 i would like to get this merged this week for preview - I will try with the files from this zip and compare with the files in this PR - I'll try to keep the history here so you have authorship (except where something differs from this `patch-1` branch and the zip).

In future it would be lovely if you could use git to make these changes so that we don't have to apply separate patches and end up with a confusing history 💖

**Comment by 1bardesign** [comment]
@kinokino7 ok it's merged 🎉 there seem to be a few minor things missing translation but it loads and the font swapping works using the same system as we used for the chinese translation - feel free to open future PRs with extended translations if you have time, it should be much easier to test now!

The font was nice and small compared to the ZN one too, which is great.

Thanks again! ✨

**Comment by kinokino7** [comment]
Thank you for confirmation.
Missing part of translation>
I can not figure out where I am missing.
So, if you show the part to you
I think I can try to retranslate the part.

**Comment by 1bardesign** [comment]
@kinokino7 the ones that stuck out were "Patreon", "Discord", "Wiki" in the main menu, as well as "Armour Set" "Royal Guard Cape" and "Cap framerate" in settings - I haven't looked incredibly closely though, just made sure that the text changed appropriately and that the new font was used, as I cannot speak Japanese personally 😅

**Comment by kinokino7** [comment]
For Japanese, 'discord' and 'wiki' can be understood even in English.

'Patreon' is a system unfamiliar to Japanese.
However, because crowdfunding is widespread,
The notation such as 'Patreon (Crowdfunding)' may be easy to understand.

"Armor Set" ="アーマーセット"
"Royal Guard Cape" =ロイヤルガードケープ
  "Cap framerate" =フレームレート取得

I think it will be a translation of

**Pull request merged**
