### PR TITLE
Temporary fix for missing knight animations

### PR DESCRIPTION
**Pull request by ferrezinhre**
## Status

**READY**

## Description

A small change that is a temporary fix for missing knight animations, until someone find right way how solve this problem.

## Steps to Test or Reproduce
uh, umm, fighting as knight?
_was tested on eu captains._

### CODE REVIEW

**Comment by bunniewormy** [comment]
hot, fuzzle was right about 1 line fix

**Comment by Franrek** [comment]
Does this shit really works?

**Comment by 1bardesign** [comment]
How come it's added twice?

**Comment by 1bardesign** [comment]
I see, no problem.

Seems unlikely to be a very successful fix (afaict a proper fix would require actually sending all the knight timers with each delta and syncing the animations up to those) - but if it improves things, I'm happy to merge it through to test at least.

**Pull request merged**
