### PR TITLE
Create Portuguese_br.json

### PR DESCRIPTION
**Pull request by MatheusGodoi**
## Status
In Development

## Description

Portuguese - Brazilian translation for the game.
Finished all tutorials, taunts, accolades, sandbox (solo), save the princess, entire ESC menu and the entire options menu too.
Re-created the PR as I reorganized the entire file so it makes more sense on the translation order, and to clean the PR a bit.

### CODE REVIEW

**Comment by 1bardesign** [comment]
Hello, is this ready for integration soon? Would be nice to have BR support.

Also: You do not need to recreate the Pull Request every time you modify things - just push to the matching branch and the pr will be updated - it looks like you are using `master` on your end 👍 👌

**Comment by MatheusGodoi** [comment]
Oh yeah, just remade it as I changed the entire file and the original PR was a bit confusing :b
I think I can finish entirely today or tomorrow, so yes :3

**Comment by 1bardesign** [comment]
Excellent thank you! 🎉

**Comment by MatheusGodoi** [comment]
Done Geti, added everything that was missing, translation cover almost the entire game now!
Its missing things not supported by the translate function yet (but already on the file, so when it gets support should work) and "the info box" that appear when you get kicked/banned from a server and try to join back, I couldn't find a file in the game folder that hold these messages to translate them.

**Comment by 1bardesign** [comment]
@MatheusGodoi seems there's been some more work since your last comment? 😄 anything more to add? if not I'll merge this through tomorrow morning.

**Comment by MatheusGodoi** [comment]
Oh yeah, found some mistakes in the file since the last comment :c

Im pretty sure its finished now, the only missing thing that I know is the kick/ban window when you reconnect a server
(Disconnected by server, Reason: something Time left: something) 

I was unable to find a file that have the strings used to make that box, so its not done yet.

For the rest its all good :3

**Comment by furai** [comment]
Hey, can you rename the file to `Portuguese_pt.json`

**Comment by MatheusGodoi** [comment]
It would be confusing no? As its Brazillian Portuguese and not from Portugal, I used the 'br'.
They are have big differences :s

**Comment by Harrison-Miller** [comment]
@Mazey suggested on discord to use Portuguese_pt-br.json as that's the official language code.

**Comment by MatheusGodoi** [comment]
Done, renamed

**Comment by furai** [comment]
http://www.localeplanet.com/icu/pt-BR/
Uh my bad then. Should have left it as it was. First part is region, second part the language. I thought it was Portuguese. My bad.

**Comment by MatheusGodoi** [comment]
So I should left it as it is now (Portuguese_pt-br) or revert to Portuguese_br?

**Comment by furai** [comment]
I think so. @Harrison-Miller, what do you think? IMO, it makes the most sense, and it was probably supposed to be like that.

**Comment by Harrison-Miller** [comment]
Thanks @MatheusGodoi sorry about the confusion and mix up.

**Pull request merged**
