### PR TITLE
[fixed] No sound when shooting your last arrow (on server) + Grapple sound on collision

### PR DESCRIPTION
**Pull request by mugg91**
## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

```
[fixed] Last arrow doesn't make a sound effect
[added] Grapple will make a sound on collision
```

Fixes https://github.com/transhumandesign/kag-base/issues/1870

This PR changes `ArcherLogic.as` to allow a shoot sound effect when shooting your last arrow(s) in online.

Sound effect removed from command `"shoot arrow"`.
A new command `"shoot sound"` is added which is sent in `CreateArrow()`. Only the client processes the command and it will play the sound effect. Some logic was added to make it play the sound only once in a tick, not three times for legolas.

This way, the sound will play when the arrow is actually created.

Tested offline and online, no problems.

## Steps to Test or Reproduce

Shoot your last arrow in online.
Notice there is no sound.
**After this PR, there is a sound.**

### CODE REVIEW

**Comment by mugg91** [comment]
I added a commit that will play a `BombBounce.ogg` sound effect when grapple collides with something.
It is processed only on client.
I tested in offline and online and it works.

I don't know if the sound will happen just with you or with all archers on the map. I have no way to test it right now but if so it should be easy to fix it.

**Comment by mugg91** [comment]
I made a small change that makes the sound play amplied by 0.5f (less annoying) and at the grapple's position rather than the archer's.

**Comment by mugg91** [comment]
In the middle of merging all my PRs, I saw `this.getShape().getConsts().net_threshold_multiplier = 0.5f;` in `ArcherLogic.as` being there for no reasons. It needs to be removed before you use this PR.

**Comment by Vam-Jam** [comment]
If you could fix up merge conflicts, I'll review it when I get a chance (if this is still an issue)

**Comment by mugg91** [comment]
I made a new PR for the grapple sound https://github.com/transhumandesign/kag-base/pull/2234
Closing this now.

**Pull request closed without merging**
