### PR TITLE
German Translation Hotfix

### PR DESCRIPTION
**Pull request by Ni-ice**
Added missing comma.

### CODE REVIEW

**Comment by Harrison-Miller** [comment]
is everything here good to go? or any more last touches?

**Comment by furai** [comment]
@Harrison-Miller I mean, yeah maybe people should add reviewers when it's ready for review or assign to people. Most likely normal people don't have that access rights....

Sooo, let's try to make people let us know in comments of PR when the PR is ready to be merged in.

**Comment by Ni-ice** [comment]
@furai @Harrison-Miller 
I'm not yet completely done, I'll let you know as soon as I've finished.

**Comment by furai** [comment]
Is this ready?

**Comment by Ni-ice** [comment]
Yes it works.

**Pull request merged**
