### PR TITLE
Team scramble vote

### LINKED ISSUE #174: [Feature pitch] Adding a team scramble vote option
I'd say that about 75% approval would have to be reached, teams are randomly scrambled if people feel like it's unbalanced. Maybe if a team votes unanimously it does it anyway?

### PR DESCRIPTION
**Pull request by eps0003**
## Status

**READY**

## Description

Adds a vote option to scramble the teams if they are unbalanced. Anyone that isn't in spectator can participate in the vote. If the vote passes, the map is restarted with new teams. Currently, the pass percentage is 50% which can be adjusted if needed.

Closes #174

## Steps to Test or Reproduce

Vote to scramble teams

### CODE REVIEW

**Comment by bunniewormy** [comment]
> If the vote passes, the map is restarted with new teams
whats the point? just vote nextmap, stalemate

**Comment by eps0003** [comment]
This gives players an option to restart the current map rather than moving to a new map.

**Comment by AsuMagic** [comment]
I will agree with @bunniewormy, I would have expected this to scramble teams but not to reset the map.

**Comment by eps0003** [comment]
@bunniewormy @AsuMagic I disagree. I don't think it would be nice if the teams were scrambled and you were forced to continue working on a half-completed base. The difference between this and one person being team swapped is that everyone is involved, not just the one person.

**Pull request merged**
