### PR TITLE
[Change] Heal sound change by dome

### PR DESCRIPTION
**Pull request by Vam-Jam**
Title ^

https://cdn.discordapp.com/attachments/601801785623052301/714840912525656095/Heart.ogg

### CODE REVIEW

**Comment by Harrison-Miller** [comment]
https://github.com/transhumandesign/kag-base/issues/762 I would like to get more feedback on adding this to the game.

I personally am not sure if I'm a fan, but I would leave it more to a vote I guess.

**Comment by butterdome** [comment]
I already tested it for a while and it works good with the game sound :)) 

here are two examples ingame: 
https://cdn.discordapp.com/attachments/337266863841214465/713048105230008392/healsound_gameplay_01.mp4
https://cdn.discordapp.com/attachments/337266863841214465/713048126365368462/healsound_gameplay_02.mp4

**Comment by Harrison-Miller** [comment]
@butterdome also where did you get this sound from we need to know the licensing.

**Comment by butterdome** [comment]
i made it myself :))

**Pull request merged**
