### PR TITLE
[modified] wrapped all strings into getTranslatedString functions

### PR DESCRIPTION
**Pull request by Diprog**
more coming soon

### CODE REVIEW

**Comment by 1bardesign** [comment]
This should not necessarily be done _everywhere_.

The one that sticks out is that requirements (from `Requirements.as`) should probably be translated for rendering, not for syncing over the net (as that might even use the server locale, not the player locale?). 

Same goes for the `rules.SetGlobalMessage("The princess died!");` - this will be done serverside, and in the server locale. We can make the rules global message be translated if you need, please just raise an issue for it after confirming that it isn't already, or maybe put it on the existing translations issue https://github.com/transhumandesign/kag-base/issues/16

**Comment by Diprog** [comment]
Oh yeah, I'll be more attentive next time (about requirements).
And I don't see any problem in translating global messages for single-player game modes

**Comment by 1bardesign** [comment]
It would be better for the engine to provide the translation for all players, and `Challenge_Save.as` is the multiplayer princess-saving challenge mode, not the single-player Save The Princess mode.

**Comment by Diprog** [comment]
Ow, thx. I'll fix everything tomorrow.

**Comment by 1bardesign** [comment]
I have a few concerns about this; it's coming along well but some things are translated at points that are maybe not the best;

- `BuildBlock`s could all be translated in one place (when the menu is created) rather than as every block is defined, which would make mods automatically translation-compatible if they have matching strings.
- `CreateSign` could just translate the string passed in rather than every create sign call having a separate translate call, or (better) the sign could translate as needed (when rendering, if no cached string is found) so that the sign is not in server locale. I'm not sure if signs are used much on any custom servers but it would still probably be nicer?
- As I said, next build `rules.SetGlobalMessage` will display translated version per-client rather than translating serverside. The global rules message is synchronised from server to client.

Otherwise it seems pretty good! If you can fix these I'll merge this soon.

**Comment by Diprog** [comment]
BuildBlocks are already translated in build menu code, global messages are already fixed too. I'll change CreateSign soon

**Comment by 1bardesign** [comment]
I can see a few places where this has missed out one or two places but I'll get it merged for now and you can pull from master again for my fixes. Thanks for your work on improving translation support!

**Comment by Diprog** [comment]
Yeah, some fixes got reverted somehow, so I didn't notice that. Thank you too.

**Comment by Diprog** [comment]
Oh yeah, replaced ыemicolons with commas -_-

**Comment by 1bardesign** [comment]
I can see a few places where this has missed out one or two places but I'll get it merged for now and you can pull from master again for my fixes. Thanks for your work on improving translation support!

**Comment by 1bardesign** [comment]
(merged in - please base any changes on what's currently in master)

Just a sidenote, I notice a lot of "accidentally" in your commits - if you're editing things separately rather than inside a "working" kag folder it might cause trouble like this. I'd recommend working from inside a working install so the files you commit are the same files you are testing.

Using a GUI client like sourcetree, gitkraken, or tower (or gitk or..) can help catch these errors if you're not already.

Either way, try to check your diffs before hitting commit!

**Pull request merged**
