### PR TITLE
Ctf maps for december

### PR DESCRIPTION
**Pull request by Panky123**
added 2 maps, edited 2 maps, 

removed 6 maps from the cycle(Punk123_Antqueen, Punk123_BlockCity, 8x_Passfest, 8x_snitchmerc, shadowor_IslandCoast, Kaggen, SJD360_Paradox).

### CODE REVIEW

**Comment by terracraft321** [comment]
Hopefully you didn't delete-delete the maps entirely. Unless the maps are 100% useless. I recommend only from a mapcycle.cfg. The modifications seem ok to me otherwise.

**Comment by terracraft321** [comment]
Sorry for asking but could you also compress the maps if it is possible. http://compresspng.com/ for example.

**Comment by terracraft321** [comment]
And running them in-game to see if they still function. I am curious for several reasons.

**Comment by 1bardesign** [comment]
Thanks, sorry for being slow to get around to this @Panky123 , moving house has been a mess!

@terracraft321 feel free to try it out yourself - it should be ok as long as the rgb values don't change for opaque pixels and the alpha values don't change either for semitransparent pixels. I'm not going to hold the pull just for unoptimised map images though 🙂

**Pull request merged**
