### PR TITLE
[added] more Russian migrant translations

### PR DESCRIPTION
**Pull request by Mazey**
## Status
**READY**
## Description
Translates MigrantSayNo and MigrantSayFriend (thanks Biuza & Nalas/Day!)

### CODE REVIEW

**Comment by Mazey** [comment]
Because the migrant says it when he needs help, and nyet sounded weird and didn’t feel right in-game. Talk to Biurza on Discord

**Comment by furai** [comment]
Then we should record English version of Help and swap that for English first. @Biurza

**Comment by Biurza** [comment]
I don't think we could record a proper "Help" for the English version. Well at least if you don't have a spare, edited file of Mr.Bin saying the line.

I'll ask Day to record a few Nyets, but as Mazey mentioned, it's gonna be a bit less fitting, since the line is played when migrants are threatened.

**Comment by furai** [comment]
And I'm sure that MM's intent was to just say no to them. Flatly deny them whatever you want.

**Comment by 1bardesign** [comment]
Closed cause https://github.com/transhumandesign/kag-base/pull/556 was merged instead

**Pull request closed without merging**
