### PR TITLE
Create steam_content_zh

### PR DESCRIPTION
**Pull request by zestybaby**

### CODE REVIEW

**Comment by zestybaby** [comment]
Renamed, should have checked that better.

**Comment by 1bardesign** [comment]
Looks ok, at least, it's Chinese where there was English now 😅 do we have anyone who can review? I can throw it into google translate but I imagine I'll get google translate quality english out.

**Comment by zestybaby** [comment]
Machine translators are always bad when it comes to Chinese and English due to massive differences between grammar. 

For reviewing this I think @Aristalia also speaks Chinese and capable of reviewing my stuff. This user has already pointed out some better suggestions in my game translation pull request.

**Comment by 1bardesign** [comment]
That would be excellent if you have time @Aristalia ! I am working on getting font-swapping support required for CJK and other language support in game now, would be awesome to get all these changes in Soon™

**Comment by Aristalia** [comment]
I'll be on it to review more!

**Comment by Aristalia** [comment]
@zestybaby is there an English original version of this that I could reference from?

**Comment by zestybaby** [comment]
> @zestybaby is there an English original version of this that I could reference from?

https://github.com/transhumandesign/kag-base/blob/master/Locales/Steam/steam_content_en.txt

**Pull request merged**
