### PR TITLE
Hide resupply text above inventory GUI if help is hidden

### PR DESCRIPTION
**Pull request by eps0003**
## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

It is very obnoxious and shouldn't need to be shoved in the face of most players.

## Steps to Test or Reproduce

1. Have resupply available
2. Toggle help with F1

### CODE REVIEW

**Comment by AsuMagic** [comment]
Random thought: Could we maybe move this + the "resupply in _x_ seconds" message in the item bar as an icon or badge in some way (but so that it remains obvious and easily discoverable even for newbies)?  
Those messages do feel like they clutter up the screen somewhat (at least at lower resolutions) but at least they're explicit.

**Comment by AsuMagic** [comment]
Forgot about this. An alternative to this PR should be worked on soon based on the above comment, probably based on one of these sprites:

resupply draft

**Comment by eps0003** [comment]
> Forgot about this. An alternative to this PR should be worked on soon based on the above comment, probably based on this sprite:
> 
> resupply icon

Who created these sprites? I was unable to find them in the KAG files.

**Comment by AsuMagic** [comment]
Superseded by #1587

**Pull request closed without merging**
