### PR TITLE
[modified] Junko accolade community contribution

### PR DESCRIPTION
**Pull request by Mazey**
## Status

- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.

## Description

Junko community accolade - organising tournaments, assisting community growth & teaching new players

### CODE REVIEW

**Review by eps0003 — APPROVED** [review]
I never actually knew Junko did so many things in the community. 👌

**Comment by Panky123** [comment]
> I never actually knew Junko did so many things in the community. 👌

No one did, because it never happened. All junko does is post broken English and challenge people to 1 vs 1 to 69. All this talk about accolade standards and then this pr comes up 🤕

**Comment by Panky123** [comment]
I would like bunnie's vote thrown out on grounds of massive trolling
Discord_wKYV4Tn8zo

**Comment by AsuMagic** [comment]
This feels too much like a meme for now TBH, so let's not.

**Pull request closed without merging**
