### PR TITLE
add experimetal basic chinese translation

### PR DESCRIPTION
**Pull request by suzumiyasmith**
Haven't be tested and no idea how to test it

### CODE REVIEW

**Comment by AsuMagic** [comment]
Put the file in the `Base/Locales` directory in your KAG setup, add a new line in `autoupdate_ignore_custom.cfg` containing `Base/Locales/Chinese_ch.json`. Ingame open settings -> misc -> languages (experimental) and choose `Chinese (ch)`. However I don't think the font used in KAG has chinese glyphs - if all you want is to test it iirc it is a .ttf font you might be able to replace easily.

**Comment by suzumiyasmith** [comment]
got this, it seems `autoupdate_ignore_custom` doesn't work
```
Downloading checksums from http://update.kag2d.com/1/linux32-client-release/App/version.txt

Downloading http://update.kag2d.com/1/linux32-client-release/App/version.txt...
file Downloads/App/version.txt
Removing unused/moved files in ./Base

MOVING UNUSED FILE:
./Base/Locales/Chinese_ch.json to ./old/./Base/Locales/Chinese_ch.json
Version file the same (key matches)
```

**Comment by AsuMagic** [comment]
What if you add a `./` before the path in the ignore file?

**Comment by suzumiyasmith** [comment]
It worked for 1 time, but gets the same result when I tried to run `sh rungame.sh` again.
Even in that successful loading, I chose Chinese in language and nothing happened.
Maybe it's due to linux issue?

**Comment by AsuMagic** [comment]
If nothing happens then loading JSON probably failed. I believe I could add an error message when this happens.
AFAIK the specific error is not shown, all the info that is given is that the JSON failed to parse in the console (press the home key). I'm not sure whether the library allows for a better error feedback.

**Comment by 1bardesign** [comment]
You may wish to try testing a very minor translation JSON to rule out parsing errors (missing comma is the most common cause) and just get basic support in place first.

Something like:
```
{
	"Players: {PLAYERCOUNT}":"人: {PLAYERCOUNT}"
}
```
(Apologies if this is the wrong translation)

And then see if this glyph shows up in the scoreboard (press TAB in-game)

Also ensure that your json file is utf8 encoded on disk.

We are looking forward to having some Chinese language support! Thank you for your efforts, and sorry for the trouble testing it!

**Comment by 1bardesign** [comment]
Also - to prevent autoupdate messing with your files, you can run KAG with `noautoupdate` command-line parameter, or add this to your `rungame.sh`! May save headaches when adding custom font and so on as well.

We will need to figure a way to support CJK font alongside existing dejavu sans fonts...

**Comment by 1bardesign** [comment]
@suzumiyasmith any progress on this? Any more help needed?

I am just reviewing and polling all PRs but this does not seem ready to merge just yet - but we would love to have chinese language support!

**Comment by suzumiyasmith** [comment]
Yeah. I'd like to work on it. But I am busy doing dealing other things these days. Probably I will be free on this weekend.

**Comment by 1bardesign** [comment]
Thanks for responding, no rush :)

**Comment by suzumiyasmith** [comment]
Now, after adding `noautoupdate` cmd arg, I can choose `Chinese(zh)` in language setting.
It does work but Chinese characters cannot be rendered, even after I copy the font `odokai.ttf`(opendesktopfonts chinese) to the `Base/GUI/Fonts` folder. 

As Asu metioned, I should replace some irrch file somewhere but I cannot find it.
> However I don't think the font used in KAG has Chinese glyphs - if all you want is to test it iirc it is a .ttf font you might be able to replace easily with a Chinese font.

Thanks.

**Comment by 1bardesign** [comment]
- Put your .ttf font in in `GUI/Fonts`
- Replace `GUI/Fonts/DejaVu/DejaVuSans-Bold.ttf` and `GUI/Fonts/DejaVu/DejaVuSans.ttf` with `GUI/Fonts/YourFontNameHere.ttf` in GUI/guiSkin.cfg

Currently only one font is supported, and I don't think fonts really exist that cover all of unicode other than a few OS fonts.
To get CJK-localised support in we will need to either
- build some kind of fallback system in here - so if a string has characters not supported by DejaVu, it can try other fonts. 
- let it swap out fonts per-locale (so put in locale file substitutions for the fonts)

**Comment by 1bardesign** [comment]
Closing this for now after over 6 months of inactivity.

@suzumiyasmith no hard feelings at all ❤️ if you want to continue on this just open a new PR and we can help you - if you join the [official discord](https://discord.gg/kag) we can help you more "directly" in the `#development` channel and work out what would be needed for good chinese translation integration. If not, best of luck with whatever you're working on!

**Pull request closed without merging**
