### PR TITLE
[modified] rewritten and edited almost all strings in Russian locale

### PR DESCRIPTION
**Pull request by Diprog**
So now it's a high-quality translation. 
Some people made their translation a month ago: https://github.com/transhumandesign/kag-base/pull/30, and they noticed that somebody else made his file an official locale. So they contacted me, said that my translation is awful (I agree with that, cause it was made in about an hour). So we collaborated and made a new better translation. I rewrote and edited almost all death tips in their translation and merged them with my file, also edited a lot of other things.

### CODE REVIEW

**Comment by 1bardesign** [comment]
Hello, can you guys (@Diprog, @Basea) sort out one "agreed" pull request and I will merge that one?

One of https://github.com/transhumandesign/kag-base/pull/30 and https://github.com/transhumandesign/kag-base/pull/31 - I will happily reference everyone in the change notes if you give me a list of names!

**Comment by Diprog** [comment]
I'll give you a list tomorrow.
It's 1:50, so everybody is sleeping.
Most of the work on translation is made by me (Diprog) and Defender Of Basea, discussed with Voxez and some other guy (I don't know his name). 
So yeah, a full list will be sent tomorrow. Good night.

**Comment by Diprog** [comment]
Made final edits. Do you I have to create a new pull request with title "[modified] final edits on Russian translation"?
I'll upload it in about 5-6 hours.

**Comment by 1bardesign** [comment]
No if you add commits here or on Basea's PR I will merge whichever one you like - the other one will be closed.

**Comment by Diprog** [comment]
Ok, I can't commit to this PR for some unknown reason, so I'll create a new PR. You'll close #30 and #31.

**Comment by Diprog** [comment]
@1bardesign finally figured out how to update this PR. Close #30 and merge this one.
List of translators:
- Diprog;
- Basea;
- Voxez;
- Grey Guard.
Thanks!

**Comment by Diprog** [comment]
I'll add a new PR tomorrow with new translatable string.
I've just translated a basics tutorial, builder blocks and a half of CTF tutorial

**Comment by Diprog** [comment]
I fucked up everything. Close this PR xD

**Comment by 1bardesign** [comment]
For the record, you can close PRs that you own as well 👍

**Pull request closed without merging**
