### PR TITLE
Taunt wheel

### LINKED ISSUE #200: [Feature Pitch] add Taunts, like in Classic
In Classic, you could click V and choose a Taunt. It was a pre-made message, which could either be normal chat or team chat, that would be sent to the chat. 

There were a variety of taunts, such as:

"For the King!"
"Run for your life!"
"Chicken!"
"Your mother was a hamster!"
"Your father smelt of elderberries!"
"I fart in your general direction!"

Some class/team ones:
"The red builder always triumphs!"
"The blue archer always triumphs!"
"My sword is bigger than your sword!"
 
Some useful team chat orders:

"Cover me!"
"Hold position!"
"Fall back!"
"MOVE!"
"Follow me"
"Rush!!!"
"Repair the castle!"
"Load the catapult!"

Some team chat alarm ones:

"Incoming!"
"Under catapult fire!"
"Trap!"
"Rush in tunnels!"

Some ordering to build stuff:

"Build a wall here!"
"Build a ladder here!"
"Build a catapult!"

And some asking for stuff:
"Need builders!"
"Need bombs!"
"Need help!

My suggestion is to bring this system back. The taunting taunts could be fun, and the team chat ones were pretty nice for teamwork. Perhaps this would get more people to teamwork in pubs. You could also add custom taunts, so people can change it themselves. It would also help with teamwork in competitive, especially if you don't use voice chat.

Of course, one problem could arise because of that; spam. But I believe it would be very easy to counter that; you could put a 10-15 second cooldown on public chat taunts, and like 2-3 seconds cooldown on team chat ones. BTW, the ignore function exists for a reason ;)

I also suggest that Taunts also show chat bubbles, and have a different option for enabling/disabling them:
image
This way you could disable normal chat bubbles [to prevent spam cluttering your screen], but you could enable taunt bubbles [so you can see your teammates asking for help/giving information]

### PR DESCRIPTION
**Pull request by eps0003**
## Status

**READY-ish**

## Description

This adds taunts just like in classic!

Summary:
- Taunt key displays taunt menu which provides quick access to common phrases/taunts
- Potentially customizable taunts
- Posts taunts in global/team chat depending on the category
- Cooldown to prevent spamming (shorter for team taunts, can be adjusted in code)
- Prevent using the same taunt in a row (currently disabled, can be changed in code)

Closes #200

## Steps to Test or Reproduce

Can't currently test since the taunt button doesn't work

### CODE REVIEW

**Comment by Shylie** [comment]
I believe you can add text to chat script-side. Check global functions, rather than `CPlayer` or whatever methods

**Comment by eps0003** [comment]
It seems like people would prefer it if taunts weren't posted in chat. It would clutter the chat and lead to spam. I don't want to add a cooldown for taunts since that would be quite restrictive.

I've managed to use `blob.Chat()` in a hacky way to allow you to see other peoples taunts, but I'm struggling to make them appear only once for each taunt.

**Comment by eps0003** [comment]
This is ready to go now, other than the fact that the taunt key is still not working.
I added spam cooldown and repeat taunt vars at the top of `TauntMenu.as` if you want to modify them.
This supports custom taunts but I'm still not sure what prevents the cfg file from being overwritten when joining a server.

**Comment by 1bardesign** [comment]
(This has conflicts now, going to need master merged in and conflicts resolved before we can merge it)

**Comment by eps0003** [comment]
Resolved conflicts

**Pull request merged**
