### PR TITLE
Chicken In Inventory

### PR DESCRIPTION
**Pull request by Blubahub**
Another simple modification, this one that I think KAG would really benefit from. It makes chickens being able to be put in a player's Inventory (1x1 space; max stacks 1).

A few examples of this being useful:

- Players want to head over into dangerous enemy territory with their chicken (to get a better vantage point to jump off and hover from), but don't want it to get hurt or killed by an enemy attack - so they put it in their Inventory!

- Easily manage chickens for chicken farms.

- Put many chickens in crates for increased storage (i.e., when too many chickens exist that they stop breeding, and they aren't being used fast enough).

And so forth. Discuss..!

### CODE REVIEW

**Comment by terracraft321** [comment]
Maybe this should have some kind of a drawback?

**Comment by FuzzCat927** [comment]
I agree with Vik, why was boulder code changed?

**Comment by Blubahub** [comment]
Hmm... Not sure. I'll set to work on fixing it now...

**Comment by 1bardesign** [comment]
@Blubahub i think you based it off your master branch with those boulder changes initially, rather than github having a glitch 😉 

I'm ok with this, needs more discussion in `#development` though probably. I can't see any real issues with it other than making chickens a little more viable though.

**Comment by Blubahub** [comment]
Sorry, I'm new to GitHub. Here's the GitHub repo @1bardesign (couldn't managed to fix my copied kag-base): https://github.com/Blubahub/chickensininv

**Comment by 1bardesign** [comment]
Hi @Blubahub - we'd love it if you could submit a "proper" pull request for these changes.

I'm sure someone can help you get a proper PR set up though the `#development` channel on discord, but [this](https://help.github.com/articles/about-pull-requests/) is the github starting point. You basically "just" need to:

- fork `kag-base`
- clone your fork locally (onto your computer, so you can work on it directly)
- check out a feature branch (`git checkout -b feature/chickens-in-inv` would be sane)
- make the changes to your local repo (copy your files in)
- add and commit the changes
- push the new branch + changes back to your fork on github
- open the pull request for that branch through github

I know it's a bit complicated, but this allows us to merge your changes cleanly into the repository, allows you to work on features in parallel (on separate branches), and lets us review your changes quickly and easily through github, rather than having to manually apply your changed files to our repository and then start review.

If you're having trouble with the command line, there are a lot of graphical clients that can make it easier to change branch, commit files, and so on without typing any commands.

Hope this helps!

**Pull request closed without merging**
