### PR TITLE
Optimized Images

### PR DESCRIPTION
**Pull request by terracraft321**
Smaller file size, for smaller download and space saving in general.
I wouldn't recommend using the maps unless they work and act normally.
Total -- 3,155.22kb -> 1,792.59kb (43.19%)

### CODE REVIEW

**Comment by 1bardesign** [comment]
Interesting idea. Honestly the images are a pretty trivial amount of the size but it's a pretty obvious win as far as I can see.

Will imgbot do this periodically? And will it be against our repo or your fork?

**Comment by 1bardesign** [comment]
@terracraft321 Would you be able to run this against the recently added TDM maps so there's not 2 separate PRs for the same thing?

**Comment by terracraft321** [comment]
@1bardesign Yes, imgbot does it always when new images are added to the repo.

**Comment by terracraft321** [comment]
And i'll re-run it.

**Pull request closed without merging**
